from __future__ import annotations

from unittest.mock import MagicMock

from click.testing import CliRunner

from synto.cli import cli
from synto.config import Config
from synto.indexer import generate_index
from synto.models import RawNoteRecord
from synto.state import StateDB


def _make_vault(tmp_path):
    (tmp_path / "raw").mkdir()
    (tmp_path / "wiki").mkdir()
    (tmp_path / "wiki" / ".drafts").mkdir()
    (tmp_path / "wiki" / "sources").mkdir()
    (tmp_path / ".synto").mkdir()
    (tmp_path / "synto.toml").write_text("[pipeline]\nauto_commit = true\n")
    return tmp_path


def test_compile_without_auto_approve_mentions_synto_approve(tmp_path, monkeypatch):
    vault = _make_vault(tmp_path)
    config = Config.from_vault(vault)
    db = StateDB(config.state_db_path)

    monkeypatch.setattr("synto.cli._load_deps", lambda cfg: (object(), db))
    monkeypatch.setattr(
        "synto.pipeline.compile.compile_concepts",
        lambda **kwargs: ([vault / "wiki" / ".drafts" / "Alpha.md"], [], {}),
    )
    monkeypatch.setattr("synto.indexer.generate_index", lambda *args, **kwargs: None)
    monkeypatch.setattr("synto.indexer.append_log", lambda *args, **kwargs: None)

    result = CliRunner().invoke(cli, ["compile", "--vault", str(vault)])

    assert result.exit_code == 0
    assert "synto approve --all" in result.output


def test_maintain_uses_synto_command_names(tmp_path, monkeypatch):
    vault = _make_vault(tmp_path)
    config = Config.from_vault(vault)
    db = StateDB(config.state_db_path)
    db.upsert_raw(RawNoteRecord(path="raw/a.md", content_hash="h1", status="ingested"))
    db.upsert_concepts("raw/a.md", ["Alpha"])
    db.mark_concept_blocked("Alpha")

    monkeypatch.setattr(
        "synto.pipeline.lint.run_lint",
        lambda *args, **kwargs: MagicMock(issues=[], health_score=100, summary="clean"),
    )
    monkeypatch.setattr("synto.pipeline.maintain.suggest_orphan_links", lambda *args, **kwargs: [])
    monkeypatch.setattr(
        "synto.pipeline.maintain.suggest_concept_merges", lambda *args, **kwargs: []
    )

    result = CliRunner().invoke(cli, ["maintain", "--vault", str(vault)])

    assert result.exit_code == 0
    assert "synto unblock" in result.output


def test_generate_index_footer_uses_synto(tmp_path):
    vault = _make_vault(tmp_path)
    config = Config.from_vault(vault)
    db = StateDB(config.state_db_path)

    index_path = generate_index(config, db)

    text = index_path.read_text(encoding="utf-8")
    assert "Auto-generated by synto" in text


def test_approve_commits_synto_dir(tmp_path, monkeypatch):
    vault = _make_vault(tmp_path)
    config = Config.from_vault(vault)
    db = StateDB(config.state_db_path)
    commit_calls = []

    monkeypatch.setattr("synto.cli._load_db", lambda cfg: db)
    monkeypatch.setattr(
        "synto.pipeline.compile.approve_drafts",
        lambda *args, **kwargs: [vault / "wiki" / "Alpha.md"],
    )
    monkeypatch.setattr("synto.indexer.generate_index", lambda *args, **kwargs: None)
    monkeypatch.setattr("synto.indexer.append_log", lambda *args, **kwargs: None)
    monkeypatch.setattr(
        "synto.git_ops.git_commit",
        lambda vault, message, paths=None: commit_calls.append((vault, message, paths)) or True,
    )

    result = CliRunner().invoke(cli, ["approve", "--vault", str(vault), "--all"])

    assert result.exit_code == 0
    assert commit_calls
    assert commit_calls[0][2] == ["wiki/", ".synto/"]
