"""
Index and log generation for the wiki.

generate_index: rewrites wiki/index.md with [[wikilinks]] in body (LLM-readable).
append_log:     appends a timestamped entry to wiki/log.md (append-only).
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from importlib.resources import files
from pathlib import Path

import frontmatter as fm_lib

from .config import Config
from .state import StateDB
from .vault import atomic_write, is_concept_article_path, parse_note, sanitize_filename, write_note

_INDEX_SCHEMA_VERSION = 1
_VAULT_PACK_VERSION = "0.0.0-vault"


def generate_index(config: Config, db: StateDB) -> Path:
    """
    Write wiki/index.md — a flat catalogue of concepts, sources, and queries.
    All entries use body [[wikilinks]] so Obsidian graph picks them up.
    Returns the path written.
    """
    now = datetime.now().strftime("%Y-%m-%d")

    # Gather published articles (not drafts, not sources/ or INDEX.md)
    articles = db.list_articles(drafts_only=False)
    published = [a for a in articles if a.is_published]

    # Separate concepts from source summaries and synthesis pages
    concept_articles = []
    source_articles = []
    synthesis_articles = []
    for art in published:
        rel = art.path
        if art.kind == "synthesis":
            synthesis_articles.append(art)
        elif "/sources/" in rel or "\\sources\\" in rel:
            source_articles.append(art)
        else:
            concept_articles.append(art)

    # Also pick up source summary pages directly from wiki/sources/ filesystem
    # (in case they were created outside of DB tracking)
    source_pages: list[tuple[str, str]] = []  # (title, link_text)
    if config.sources_dir.exists():
        for md in sorted(config.sources_dir.glob("*.md")):
            try:
                meta, _ = parse_note(md)
                title = meta.get("title", md.stem)
                quality = meta.get("quality", "")
                src_file = meta.get("source_file", "")
                hint = quality if quality else src_file
                source_pages.append((title, hint))
            except Exception:
                source_pages.append((md.stem, ""))

    # Build concept entries from DB
    concept_entries: list[tuple[str, str]] = []
    for art in sorted(concept_articles, key=lambda a: a.title.lower()):
        concept_entries.append((art.title, ""))

    # Also scan wiki/ root for published .md not in DB (safe fallback)
    known_titles = {a.title for a in concept_articles}
    if config.wiki_dir.exists():
        for md in sorted(config.wiki_dir.glob("*.md")):
            # Skip index + log (any case, covers legacy INDEX.md from pre-v0.5 vaults)
            if md.name.lower() in ("index.md", "log.md"):
                continue
            try:
                meta, _ = parse_note(md)
                title = meta.get("title", md.stem)
                if title not in known_titles:
                    concept_entries.append((title, ""))
                    known_titles.add(title)
            except Exception:
                pass

    # Build index body
    body_lines = [
        "# Wiki Index",
        "",
    ]

    if concept_entries:
        body_lines.append("## Concepts")
        for title, hint in concept_entries:
            safe = sanitize_filename(title)
            link = f"[[{safe}|{title}]]" if safe != title else f"[[{title}]]"
            entry = f"- {link}"
            if hint:
                entry += f" — {hint}"
            body_lines.append(entry)
        body_lines.append("")

    if source_pages:
        body_lines.append("## Sources")
        for title, hint in source_pages:
            safe = sanitize_filename(title)
            link = f"[[{safe}|{title}]]" if safe != title else f"[[{title}]]"
            entry = f"- {link}"
            if hint:
                entry += f" — {hint}"
            body_lines.append(entry)
        body_lines.append("")

    if synthesis_articles:
        body_lines.append("## Synthesis")
        synthesis_entries = sorted(
            synthesis_articles,
            key=lambda a: (-a.created_at.timestamp(), a.title.casefold()),
        )
        visible_entries = synthesis_entries[:25]
        for art in visible_entries:
            safe = Path(art.path).stem
            link = f"[[{safe}|{art.title}]]" if safe != art.title else f"[[{art.title}]]"
            body_lines.append(f"- {link}")
        if len(synthesis_entries) > len(visible_entries):
            hidden_count = len(synthesis_entries) - len(visible_entries)
            body_lines.append(f"_({hidden_count} more synthesis pages not shown)_")
        body_lines.append("")

    total = len(concept_entries) + len(source_pages) + min(len(synthesis_articles), 25)
    body_lines.append(f"_Auto-generated by synto. {total} entries._")

    meta = {"title": "Wiki Index", "tags": ["meta", "index"], "updated": now}
    index_path = config.wiki_dir / "index.md"
    post = fm_lib.Post("\n".join(body_lines), **meta)
    atomic_write(index_path, fm_lib.dumps(post) + "\n")
    return index_path


def index_schema_path() -> Path:
    return Path(str(files("synto") / "schemas" / "index-v1.json"))


def generate_index_json(config: Config, db: StateDB) -> Path:
    out_path = config.app_dir / "INDEX.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = _build_index_payload(config, db)
    _atomic_write_json(out_path, payload)
    return out_path


def _build_index_payload(config: Config, db: StateDB) -> dict[str, object]:
    records = sorted(
        [
            record
            for record in db.list_articles()
            if record.is_published
            and record.kind == "concept"
            and is_concept_article_path(record.path)
        ],
        key=lambda record: ((record.article_id or ""), record.path.casefold()),
    )
    articles = [
        {
            "id": record.article_id or "",
            "name": record.title,
            "path": record.path,
            "summary": None,
            "tags": [],
            "aliases": db.aliases_for_concept(record.title),
            "confidence": "high",
        }
        for record in records
    ]

    return {
        "schema_version": _INDEX_SCHEMA_VERSION,
        "pack": {
            "id": _vault_id(config),
            "name": config.vault.name,
            "version": _VAULT_PACK_VERSION,
            "language": _detect_languages(db),
            "capabilities": sorted(_compute_capabilities(db)),
        },
        "articles": articles,
        "terms": [],
        "papers": [],
        "sources": _list_sources(db),
        "source_concepts": _list_source_concept_seeds(db),
        "synthesis": _list_synthesis(db),
        "stats": _compute_stats(db),
    }


def _vault_id(config: Config) -> str:
    return hashlib.sha256(str(config.vault.resolve()).encode("utf-8")).hexdigest()[:16]


def _compute_capabilities(db: StateDB) -> set[str]:
    caps = {"articles", "concepts"}
    if db.count_source_segments() > 0:
        caps.update({"segments", "lifecycle"})
    return caps


def _detect_languages(db: StateDB) -> list[str]:
    languages = db.list_note_languages()
    return languages or ["en"]


def _list_sources(db: StateDB) -> list[dict[str, object]]:
    return [
        {"id": source_id, "title": title, "source_type": source_type}
        for source_id, title, source_type in db.list_source_documents()
    ]


def _list_source_concept_seeds(db: StateDB) -> list[dict[str, object]]:
    return [
        {
            "source_path": source_path,
            "content_hash": content_hash,
            "concepts": concepts,
        }
        for source_path, content_hash, concepts in db.list_source_concept_seeds()
    ]


def _list_synthesis(db: StateDB) -> list[dict[str, str]]:
    return [{"path": path, "title": title} for path, title in db.list_synthesis_articles_brief()]


def _compute_stats(db: StateDB) -> dict[str, object]:
    article_records = db.list_articles()
    article_count = sum(1 for record in article_records if record.is_published)
    draft_count = sum(1 for record in article_records if record.is_draft)
    return {
        "article_count": article_count,
        "draft_count": draft_count,
        "concept_count": db.count_concepts(),
        "alias_count": db.count_aliases(),
        "knowledge_item_count": db.count_knowledge_items(),
        "source_count": len(db.list_source_documents()),
        "source_segment_count": db.count_source_segments(),
        "failed_note_count": db.count_failed_notes(),
        "failed_concept_count": db.count_failed_concepts(),
    }


def _atomic_write_json(path: Path, data: dict[str, object]) -> None:
    text = json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    atomic_write(path, text)


def append_log(config: Config, entry: str) -> Path:
    """
    Append a timestamped entry to wiki/log.md (append-only).
    Creates log.md with header if it doesn't exist.
    Returns the path.
    """
    log_path = config.wiki_dir / "log.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    if not log_path.exists():
        log_path.parent.mkdir(parents=True, exist_ok=True)
        write_note(log_path, {"title": "Operation Log", "tags": ["meta"]}, "# Operation Log\n")

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"\n## [{now}] {entry}\n")

    return log_path
